### ISSUE TITLE
Background Tab Text Color applied to menu items on Windows

### ISSUE THREAD

**Issue by Osmose** [mozilla/FirefoxColor#355]
A user on reddit [commented](https://www.reddit.com/r/firefox/comments/8pnwqp/color_firefox_xp/e0e0xhe/) that a theme I made (that has a white background tab text color) was rendering the text for the hamburger menu invisible:

![](https://i.imgur.com/xECR4Ys.png)

Changing the background tab text color makes the text readable again:

![](https://i.imgur.com/CoDWIjf.png)

**Comment by Softvision-AndreeaCupsa** [comment]
@Hi Osmose, thanks for reporting this issue.
I tried reproducing this issue but unfortunately I couldn't.
I see in the screenshot that there are some add-ons installed and there might be the possibility that an add-on is in conflict with Firefox Color. In order to verify this, can you please ask the user to test if this issue is reproducible on a new Firefox profile (https://goo.gl/AWo6h8) without any other add-ons installed, but only Firefox Color?
If the issue is not reproducible with a new clean profile, can he please provide a copy of the "about:support" page?

**Comment by ThxAndBye** [comment]
Hey, I'm the one who posted the screenshots on Reddit. I've dug a little into that myself.  
I can assure you that the problem doesn't lie with any of the add-ons installed and it's also gone with a new profile.  

I've remembered that I've applied some css to Firefox via the userChrome.css to (amongst other things) make the bookmarks-bar only show on "new tab" (please make that a easy option in the settings and not 9-lines of css in some file somewhere in appdata btw.) but also to apply a dark theme for FireFox Quantum right after the release.

The css in question that causes the issue is:  

```css 
#main-window[lwthemetextcolor="bright"] .panel-arrow { filter: invert(33%); }

.panel-subview-body,#appMenu-zoomReset-button,.panel-mainview,.panel-subviews {

color: var(--lwt-text-color) !important;

background: var(--url-and-searchbar-background-color) !important;} */

.panel-subview-footer,[class^="PanelUI-"] {

color: var(--lwt-text-color) !important;

background: var(--toolbar-bgcolor) !important;}
```

It would still be a nice idea to decouple the colors of the menu from the rest of the option though.
